### ISSUE TITLE
Arch AUR package

### ISSUE THREAD

**Issue by SamWhited** [opthomas-prime/xmpp-webhook#2]
Hello, this isn't really an issue but I didn't see a preferred contact mechanism in the readme, so please pardon the noise.

I just wanted to let you know that I've created a package in the Arch User Repository (AUR) for this webhook; it can be found here: [`prometheus-xmpp-webhook`](https://aur.archlinux.org/packages/prometheus-xmpp-webhook/).

If you want to take ownership of the package, or have any requests or concerns please let me know either here, in the comments on the package, my JID (`xmpp:sam@samwhited.com?message`) or `SamWhited` on FreeNode, Mozilla, or GeekShed.

**Comment by opthomas-prime** [comment]
Hi Sam, that's great! Thanks for that. I don't have any concerns about this.
You seem to have some proper experience with Jabber - may i ask you about some stuff?

**Comment by SamWhited** [comment]
On December 9, 2018 5:59:34 PM UTC, Thomas Maier <notifications@github.com> wrote:
>Hi Sam, that's great! Thanks for that. I don't have any concerns about
>this.
>You seem to have some proper experience with Jabber - may i ask you
>about some stuff?

Sure thing; I'm not at a computer right this second, but I'll answer when I can. The jdev muc might also be a good place to ask: xmpp:jdev@conference.jabber.org?join
