### ISSUE TITLE
Support for  DIGEST-MD5  SCRAM-SHA-1

### ISSUE THREAD

**Issue by kishorerv93** [opthomas-prime/xmpp-webhook#4]
Hi, 

I really like this web-hook, We use openfire in production. I would love to suggest/ request to add a feature to support DIGEST-MD5  SCRAM-SHA-1 mechanism instead of just plain.

**Comment by opthomas-prime** [comment]
Unfortunately https://github.com/atomatt/go-xmpp (which is uesd for the webhook) only support PLAIN. But i want to refactor this project anyway soon. I'll keep the request in mind!

**Comment by alexanderadam** [comment]
Maybe it would be good to keep this issue and [issue 1](https://github.com/opthomas-prime/xmpp-webhook/issues/1) open to track them. :wink:
